# Generated by Django 4.2.16 on 2025-01-20 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(max_length=255, verbose_name='Город')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура')),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Максимальная температура')),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Минимальная температура')),
                ('humidity', models.PositiveSmallIntegerField(verbose_name='Влажность')),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скорость ветра')),
                ('wind_direction', models.PositiveSmallIntegerField(verbose_name='Направление ветра')),
                ('weather', models.CharField(max_length=255, verbose_name='Погода')),
                ('weather_desc', models.TextField(verbose_name='Описание погоды')),
                ('timestamp', models.DateField()),
                ('sunrise', models.DateField()),
                ('sunset', models.DateField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'история запросов',
                'verbose_name_plural': 'Истории запросов',
                'db_table': 'history',
                'ordering': ('id',),
            },
        ),
    ]
