# Generated by Django 4.2.16 on 2025-01-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='sity',
            new_name='city',
        ),
    ]
