# Generated by Django 4.2.16 on 2025-02-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_rename_sity_userhistory_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='sunrise',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='sunset',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
